### ISSUE TITLE
six is required to be installed prior to awssig

### ISSUE THREAD

**Issue by slyapustin** [dacut/python-aws-sig#2]
There reference to the `six` in the [setup.py](https://github.com/dacut/python-aws-sig/blob/master/setup.py#L3), it should be installed before `awssig` https://github.com/dacut/python-aws-sig/blob/master/setup.py#L3

**Comment by slyapustin** [comment]
From the docs: 

> Note: projects listed in setup_requires will NOT be automatically installed on the system where the setup script is being run. They are simply downloaded to the ./.eggs directory if they’re not locally available already. If you want them to be installed, as well as being available when the setup script is run, you should add them to install_requires and setup_requires.


https://setuptools.readthedocs.io/en/latest/setuptools.html

**Comment by dacut** [comment]
Good point; not sure what I was doing there.

**Comment by dacut** [comment]
This is fixed in https://github.com/dacut/python-aws-sig/commit/4efe89b9d2fe4c20f45f58fcd26aa3ef15fa32ef and released in 0.3.2.

**Comment by slyapustin** [comment]
Great, thank you @dacut !
